WALL = '+'
SPRITE = 'i'
SPRITE_T = 'I'

EMPTY = ' '
TARGET = 'o'
BOX_NS = '!'
BOX_S = '.'

RESTART = ' '
QUIT = 'q'

CONTROLS = "wasd q"

board = [
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL],
    [WALL, EMPTY, BOX_S, EMPTY, EMPTY, EMPTY, EMPTY, WALL],
    [WALL, SPRITE, EMPTY, BOX_NS, EMPTY, TARGET, EMPTY, WALL],
    [WALL, EMPTY, EMPTY, EMPTY, BOX_NS, EMPTY, TARGET, WALL],
    [WALL, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, WALL],
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL]
]

TEST_CASE_15_BOARD = [
    [EMPTY, EMPTY, WALL, WALL, WALL, WALL, WALL, EMPTY],
    [WALL, WALL, WALL, EMPTY, EMPTY, EMPTY, WALL, EMPTY],
    [WALL, TARGET, SPRITE, BOX_NS, EMPTY, EMPTY, WALL, EMPTY],
    [WALL, WALL, WALL, EMPTY, BOX_NS, TARGET, WALL, EMPTY],
    [WALL, TARGET, WALL, WALL, BOX_NS, EMPTY, WALL, EMPTY],
    [WALL, EMPTY, WALL, EMPTY, TARGET, EMPTY, WALL, WALL],
    [WALL, BOX_NS, EMPTY, BOX_S, BOX_NS, BOX_NS, TARGET, WALL],
    [WALL, EMPTY, EMPTY, EMPTY, TARGET, EMPTY, EMPTY, WALL],
    [WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL]
